kind: pipeline
type: docker
name: default

steps:

- name: configure gcloud
  image: docker.io/kameshsampath/drone-gcloud-auth
  pull: never
  settings:
    google_application_credentials:
      from_secret: google_application_credentials
    google_cloud_project:
      from_secret: google_cloud_project
    registry_locations:
      - asia-south1
      - us-central1
  volumes:
    - name: gcloud-config
      path: /root/.config/gcloud
    - name: docker-config
      path: /root/.docker

- name: log the config
  image: docker.io/kameshsampath/drone-gcloud-auth
  pull: never
  commands:
    - gcloud config list
    - cat /root/.docker/config.json
  volumes:
    - name: gcloud-config
      path: /root/.config/gcloud
    - name: docker-config
      path: /root/.docker

volumes:
  - name: gcloud-config
    temp: {}
  - name: docker-config
    temp: {}
