kind: pipeline
type: docker
name: default

steps:

- name: configure gcloud
  image: docker.io/kameshsampath/drone-gcloud-auth
  pull: if-not-exists
  settings:
    google_cloud_project:
      from_secret: google_cloud_project
    registry_locations:
       - asia-south1
       - us-central1
  volumes:
    - name: gcloud-config
      path: /root/.config/gcloud

- name: log the config
  image: docker.io/kameshsampath/drone-gcloud-auth
  pull: if-not-exists
  commands:
    - gcloud config list
  volumes:
    - name: gcloud-config
      path: /root/.config/gcloud

volumes:
  - name: gcloud-config
    temp: {}
